const dummyMedicines = [
  {
    id: 1,
    name: "Acetaminophen",
    description: "Pain reliever and fever reducer.",
    price: 4.99,
    stock: 150,
    category: "Pain Relief",
    manufacturer: "Generic Pharmaceuticals",
    image: "https://example.com/acetaminophen.jpg",
  },
  {
    id: 2,
    name: "Ibuprofen",
    description: "Reduces pain, fever, and inflammation.",
    price: 6.5,
    stock: 100,
    category: "Pain Relief",
    manufacturer: "Advil",
    image: "https://example.com/ibuprofen.jpg",
  },
  {
    id: 3,
    name: "Multivitamin",
    description: "Daily vitamin and mineral supplement.",
    price: 12.99,
    stock: 75,
    category: "Vitamins",
    manufacturer: "Centrum",
    image: "https://example.com/multivitamin.jpg",
  },
  {
    id: 4,
    name: "Vitamin D3",
    description: "Supports bone health and immune function.",
    price: 8.75,
    stock: 120,
    category: "Vitamins",
    manufacturer: "Nature's Bounty",
    image: "https://example.com/vitamind3.jpg",
  },
  {
    id: 5,
    name: "Cetirizine",
    description: "Antihistamine for allergy relief.",
    price: 9.25,
    stock: 90,
    category: "Allergy",
    manufacturer: "Zyrtec",
    image: "https://example.com/cetirizine.jpg",
  },
  {
    id: 6,
    name: "Loratadine",
    description: "Non-drowsy allergy relief.",
    price: 7.8,
    stock: 110,
    category: "Allergy",
    manufacturer: "Claritin",
    image: "https://example.com/loratadine.jpg",
  },
  {
    id: 7,
    name: "Omeprazole",
    description: "Reduces stomach acid production.",
    price: 11.5,
    stock: 80,
    category: "Digestive Health",
    manufacturer: "Prilosec",
    image: "https://example.com/omeprazole.jpg",
  },
  {
    id: 8,
    name: "Loperamide",
    description: "Anti-diarrheal medication.",
    price: 5.5,
    stock: 130,
    category: "Digestive Health",
    manufacturer: "Imodium",
    image: "https://example.com/loperamide.jpg",
  },
  {
    id: 9,
    name: "Saline Nasal Spray",
    description: "Relieves nasal congestion.",
    price: 3.99,
    stock: 160,
    category: "Respiratory",
    manufacturer: "Generic Pharmaceuticals",
    image: "https://example.com/saline_nasal_spray.jpg",
  },
  {
    id: 10,
    name: "Cough Drops",
    description: "Soothes sore throats and coughs.",
    price: 2.75,
    stock: 180,
    category: "Respiratory",
    manufacturer: "Halls",
    image: "https://example.com/cough_drops.jpg",
  },
];

export default dummyMedicines;
